global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "triton"
    static_configs:
      - targets: ["triton:8002"]

